name = "ConvexBodyProximityQueries"
uuid = "e9983d58-8b29-5530-8046-db49618142f9"
authors = ["Arun Lakshmanan <lakshma2@illinois.edu>"]
version = "0.1.1"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
julia = "1.0"

[extras]
GeometryTypes = "4d00f742-c7ba-57c2-abde-4428a4b178cb"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["GeometryTypes", "Test"]
